"""HTML report generation with radar chart and detailed feedback."""

from __future__ import annotations

import os
import datetime

from interview_coach.scorer import (
    SessionScore, ScoredAnswer, DIMENSIONS,
)


_CHART_JS_CDN = "https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"

_CSS = r"""
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:"Microsoft YaHei","PingFang SC","Helvetica Neue",sans-serif;background:#f0f2f5;color:#333;line-height:1.6}
.container{max-width:900px;margin:0 auto;padding:24px}
.header{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;padding:40px 32px;border-radius:16px;margin-bottom:24px;text-align:center}
.header h1{font-size:28px;margin-bottom:8px}
.header .meta{font-size:14px;opacity:.85}
.score-overview{display:flex;justify-content:center;margin-bottom:24px}
.score-circle{width:140px;height:140px;border-radius:50%;background:linear-gradient(135deg,#667eea,#764ba2);display:flex;flex-direction:column;align-items:center;justify-content:center;color:#fff}
.score-circle .number{font-size:48px;font-weight:700}
.score-circle .label{font-size:13px;opacity:.8;margin-top:2px}
.card{background:#fff;border-radius:12px;padding:24px;margin-bottom:20px;box-shadow:0 2px 8px rgba(0,0,0,.06)}
.card h2{font-size:18px;margin-bottom:16px;padding-bottom:8px;border-bottom:2px solid #667eea;display:flex;align-items:center}
.card h2 .icon{margin-right:8px;font-size:20px}
.chart-wrap{max-width:450px;margin:0 auto}
.dim-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px}
.dim-item{background:#f8f9ff;border-radius:8px;padding:14px;text-align:center}
.dim-item .dim-name{font-size:13px;color:#666;margin-bottom:4px}
.dim-item .dim-score{font-size:28px;font-weight:700;color:#667eea}
.dim-item .dim-max{font-size:11px;color:#999}
.strengths-list,.weaknesses-list{list-style:none}
.strengths-list li,.weaknesses-list li{padding:8px 12px;margin-bottom:6px;border-radius:6px;font-size:14px}
.strengths-list li{background:#e8f5e9;color:#2e7d32}
.weaknesses-list li{background:#fce4ec;color:#c62828}
.qa-section{margin-top:8px}
.qa-block{border-left:3px solid #667eea;padding:12px 16px;margin-bottom:16px;background:#fafbff;border-radius:0 8px 8px 0}
.qa-block .q{font-weight:600;color:#555;margin-bottom:6px;font-size:14px}
.qa-block .a{color:#333;font-size:14px;margin-bottom:8px;white-space:pre-wrap}
.qa-block .qa-meta{display:flex;gap:16px;font-size:12px;color:#999}
.feedback-text{background:#fff3e0;border-left:4px solid #ff9800;padding:16px;border-radius:0 8px 8px 0;margin-top:8px;font-size:14px;line-height:1.7}
.footer{text-align:center;color:#999;font-size:12px;margin-top:32px;padding-top:16px;border-top:1px solid #e0e0e0}
"""


_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>AI模拟面试报告 - {role} - {date}</title>
<style>{css}</style>
</head>
<body>
<div class="container">

  <div class="header">
    <h1>AI 模拟面试报告</h1>
    <div class="meta">
      目标岗位：{role} &nbsp;|&nbsp; 难度：{difficulty} &nbsp;|&nbsp;
      轮次：{rounds} &nbsp;|&nbsp; 日期：{date}
    </div>
  </div>

  <div class="score-overview">
    <div class="score-circle">
      <span class="number">{total_score}</span>
      <span class="label">综合评分 / 100</span>
    </div>
  </div>

  <div class="card">
    <h2><span class="icon">&#x1F4CA;</span>维度得分雷达图</h2>
    <div class="chart-wrap">
      <canvas id="radarChart" width="400" height="400"></canvas>
    </div>
    <div class="dim-list" style="margin-top:16px;">
      {dim_cards}
    </div>
  </div>

  <div class="card">
    <h2><span class="icon">&#x2705;</span>亮点优势</h2>
    <ul class="strengths-list">
      {strengths}
    </ul>
  </div>

  <div class="card">
    <h2><span class="icon">&#x26A0;&#xFE0F;</span>待改进方向</h2>
    <ul class="weaknesses-list">
      {weaknesses}
    </ul>
  </div>

  <div class="card">
    <h2><span class="icon">&#x1F4AC;</span>逐题回放与评分</h2>
    <div class="qa-section">
      {qa_blocks}
    </div>
  </div>

  <div class="card">
    <h2><span class="icon">&#x1F4DD;</span>面试官综合评价</h2>
    <div class="feedback-text">
      {overall_feedback}
    </div>
  </div>

  <div class="footer">
    Generated by AI Interview Coach v{version} &mdash; {date}
  </div>

</div>
<script src="{chart_js}"></script>
<script>
(function(){{
  var ctx=document.getElementById('radarChart').getContext('2d');
  new Chart(ctx,{{
    type:'radar',
    data:{{
      labels:{labels},
      datasets:[{{
        label:'维度得分',
        data:{data},
        backgroundColor:'rgba(102,126,234,0.2)',
        borderColor:'rgba(102,126,234,1)',
        borderWidth:2,
        pointBackgroundColor:'rgba(102,126,234,1)',
        pointBorderColor:'#fff',
        pointHoverRadius:6,
      }}]
    }},
    options:{{
      responsive:true,
      scales:{{
        r:{{
          beginAtZero:true,
          max:20,
          min:0,
          ticks:{{stepSize:4,fontSize:11}},
          pointLabels:{{fontSize:13,color:'#333'}}
        }}
      }},
      plugins:{{legend:{{display:false}}}}
    }}
  }});
}})();
</script>
</body>
</html>"""


def _dim_card_html(name_cn: str, score_val: float) -> str:
    return (
        f'<div class="dim-item">'
        f'<div class="dim-name">{name_cn}</div>'
        f'<div class="dim-score">{score_val:.0f}</div>'
        f'<div class="dim-max">/ 20</div>'
        f'</div>'
    )


def _qa_block_html(a: ScoredAnswer, idx: int) -> str:
    dim_text = "  |  ".join(
        f"{d.name_cn}: {a.dim_scores.get(d.name, 0)}/20"
        for d in DIMENSIONS
    )
    return (
        f'<div class="qa-block">'
        f'<div class="q">Q{idx}: [{a.category}] {a.question_text}</div>'
        f'<div class="a">{a.answer}</div>'
        f'<div class="qa-meta">本题得分: {a.total_score}/100 &nbsp;|&nbsp; {dim_text}</div>'
        f'</div>'
    )


def _build_overall_feedback(session: SessionScore, role: str) -> str:
    parts = []
    avg = session.total_score
    if avg >= 85:
        parts.append(f"综合评价：优秀。你在{role}岗位的模拟面试中表现出色，各方面素质均衡。")
        parts.append("建议在维护当前水平的同时，持续关注行业前沿动态，保持竞争力。")
    elif avg >= 70:
        parts.append(f"综合评价：良好。你在{role}岗位面试中展现了扎实的基础，但部分维度还需加强。")
        parts.append("建议针对弱项进行针对性练习，尤其是结构化表达和深度思考方面。")
    elif avg >= 55:
        parts.append(f"综合评价：一般。你在{role}面试中能够基本回答问题，但整体表现还有较大提升空间。")
        parts.append("强烈建议系统性准备：多做STAR练习、深入研究目标公司业务、提升回答的深度与结构感。")
    else:
        parts.append(f"综合评价：需要提升。你的{role}面试准备还不够充分，多项核心能力需要加强。")
        parts.append("建议从基础开始：每天练习2-3道面试题，录制自己的回答并复盘，逐步建立自信。")

    if session.overall_weaknesses:
        parts.append(f"重点改进方向：{'、'.join(session.overall_weaknesses[:3])}。")

    return "<br><br>".join(parts)


def generate_html_report(
    session: SessionScore,
    role: str = "产品经理",
    difficulty: str = "medium",
    rounds: int = 5,
) -> str:
    """Generate a self-contained HTML report from a scored interview session."""

    now = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d %H:%M")

    dim_cards_html = "\n      ".join(
        _dim_card_html(d.name_cn, session.dim_averages.get(d.name, 0))
        for d in DIMENSIONS
    )

    strengths_html = "\n      ".join(
        f"<li>{s}</li>" for s in (session.overall_strengths or ["暂无评估数据"])
    )
    weaknesses_html = "\n      ".join(
        f"<li>{w}</li>" for w in (session.overall_weaknesses or ["暂无评估数据"])
    )

    qa_blocks_html = "\n      ".join(
        _qa_block_html(a, i + 1) for i, a in enumerate(session.scores)
    )

    labels = [d.name_cn for d in DIMENSIONS]
    data = [session.dim_averages.get(d.name, 0) for d in DIMENSIONS]

    overall = _build_overall_feedback(session, role)

    from interview_coach import __version__

    html = _HTML_TEMPLATE.format(
        role=role,
        difficulty=difficulty,
        rounds=rounds,
        date=date_str,
        total_score=session.total_score,
        dim_cards=dim_cards_html,
        strengths=strengths_html,
        weaknesses=weaknesses_html,
        qa_blocks=qa_blocks_html,
        overall_feedback=overall,
        labels=labels,
        data=data,
        css=_CSS,
        chart_js=_CHART_JS_CDN,
        version=__version__,
    )

    return html


def save_report(html: str, output_dir: str, role: str = "candidate") -> str:
    """Save the HTML report to a file and return the path."""
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"interview_report_{role}_{timestamp}.html"
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)
    return filepath
